# -*- coding: utf-8 -*-
"""Text_Summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPrrq0uXoiqP4EwTkXg4mK27DjKjm1P3
"""

# Install required packages
!pip install -q gradio transformers

import gradio as gr
from transformers import pipeline

# Load high-quality summarizer model
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# Summarization function
def summarize_text(text):
    if not text.strip():
        return "⚠️ Please enter some text to summarize."

    # Chunk text if it's too long
    max_chunk = 1024
    chunks = [text[i:i+max_chunk] for i in range(0, len(text), max_chunk)]

    summary = ""
    for chunk in chunks:
        result = summarizer(chunk, max_length=180, min_length=40, do_sample=False)
        summary += result[0]['summary_text'].strip() + "\n"

    return summary.strip()

# Gradio GUI
gr.Interface(
    fn=summarize_text,
    inputs=gr.Textbox(label="Text Input", lines=12, placeholder="Paste article, essay, or paragraph..."),
    outputs=gr.Textbox(label="High-Quality Summary", lines=6),
    title="🧠 Advanced Text Summarizer",
    description="Uses BART-large to summarize long or short text accurately and grammatically."
).launch(debug=False, share=True)